dist: trusty
before_install:
- sudo apt-get -qq update
- sudo apt-get -qq -y install binfmt-support qemu qemu-user-static debootstrap kpartx
  lvm2 dosfstools apt-cacher-ng parted
script:
- sudo ./raspbian/build_raspbian_sd_card.sh
before_deploy:
- export RELEASE_FILE_NAME=$(ls ${HOME}/build/${TRAVIS_REPO_SLUG}/rpi/images/fabscanpi_basic_jessie_*.img)
- export MD5=$(md5sum ${RELEASE_FILE_NAME} | cut -d ' ' -f 1)
- export SHA1=$(sha1sum ${RELEASE_FILE_NAME} | cut -d ' ' -f 1)
- touch MD5:"${MD5}"
- touch SHA1:"${SHA1}"
- echo "deploying $RELEASE_FILE_NAME to GitHub releases"
deploy:
  file_glob: true
  provider: releases
  skip_cleanup: true
  api_key:
    secure: N8oPoOeaurOcXHLef8Ucp1UTKCigFnRQeM8LJGwA7o9yPutavwIHjvES9HV/Sr62G6q0FN2JOgIGc4A7fUX1QWdsVIol7Wunkq5bMuwokgv6d/CoWJlQxpGdvZx1UAO4517HpSvx/QT7/yPjRxYtTHkGwzmkQCgqDBa6kETUnp1x3UXJl1lk9AMWO7sTjYLZ9DMNcwhPHQx5l94J0Lk3MUmPthClACgruRckvgeCGg8Jr7NA5gfforgkH1m/t28k6EOw+SiW1uE4GvOLtcpqvRns9hCKNoIzPRi1k4r3TgIat27p4v8PR8rbhvDgy0qTxrzly1ja42bR3+HWp2mpkWcOwzLQpMJsjmEHS7iP861FiCM7HLlw3gvLsGxBEA5VOgjoWCpn4B9dTUHU1fyKvyX2ZjuGidxcIqM/IXBdfX+ZEQA01ZVTl4zk4OWPQt/DQ0Ju3XlJmIUJBm9k98wFns5cFUWmEwxMV2Eez2umclzAvIqsXysxzFSNbFStZnMRqIRS+S7ulhtCSsgE/1I1/VLOEuNFB/0zewtyRsCL/4YyAkO/3RI3Og5W3LZSP40LQ3t5rmO0TiLHsPdqUV5w+VyZMzF77m3gxVSXGawU/n4rKjmtskZCwLROOAeAVBg0Svl19wRnsq4ZZeTgEFQV3bmCqxaSRPrqpn0iVlrON+w=
  file:
  - "${RELEASE_FILE_NAME}"
  - MD5:${MD5}
  - SHA1:${SHA1}
  on:
    tags: true
