dist: trusty
group: deprecated-2017Q2
before_install:
- sudo apt-get -qq update
- sudo apt-get -qq -y install binfmt-support qemu qemu-user-static debootstrap kpartx
  lvm2 dosfstools apt-cacher-ng parted zip
script:
- sudo ./raspbian/build_raspbian_sd_card.sh $TRAVIS_TAG
before_deploy:
- export RELEASE_FILE_NAME="rpi/images/fabscanpi_basic_jessie_${TRAVIS_TAG}"
- export MD5=$(md5sum ${RELEASE_FILE_NAME} | cut -d ' ' -f 1)
- export SHA1=$(sha1sum ${RELEASE_FILE_NAME} | cut -d ' ' -f 1)
- touch MD5:"${MD5}"
- touch SHA1:"${SHA1}"
- echo "deploying $RELEASE_FILE_NAME to GitHub releases"
before_deploy:
- cp rpi/images/fabscanpi_basic_jessie_$TRAVIS_TAG.img .
- zip fabscanpi_basic_jessie_$TRAVIS_TAG.zip fabscanpi_basic_jessie_$TRAVIS_TAG.img
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "bA9dkNhlV726rQJieGXbCwMF/9lYt0pW+pGr/rVqWSivRB5JUrxqFEuVuXt0zcppAkLFVfSRlprBZORHf9Xomw1i4QCK449n1kBO0XeKH+Ayu4hnjmfM3hoklOraxl49e/T2WkxJMMLv+g60eyu6TtqBkVvVNK6BvVp4J5DwtpbUragjRt2gH996cibuz60ZKMMFevTFCOioTNVr3mgNF7tUj8s5qtPqC/QedvOJKfT9s7/DGayox0CRa7bjY5HwihKaPEHab4ZNvAHC+Noen/A06YN9zvs/r6mclOGG5Ak2oevjIVJLKWoJt52q/M2egWRA66hF7u2WtH1SNRsxLrMY1V6vhi/i4/CGNxQg3ByM2JzJ01mQOU1Pl0LavViz/u62SUogVc0vEe+aQa1ib0ywZv0ypQwmxkf7jBGTWiieLQouLLKuXpLRNAO7oFVD4XWbd5t9cV5qi97FnZc1TijO8wxW2zwbS+rTqZDajqg9rmWYVlgCWA4p8OPyNKW8+VcYj0H6YDdmMwMPc2gu99p7bV/UsdR8KmJLtVpDYG35lfxpfBBlq6E/yFepLsHlKT+EYHMpsFCq34T9sjXfMqqMDWH+1nvz+4ZTsEYwoGoIb5a2ZFoehF85vafn23S+fyKtEi2DPDx/y4jb1DkLBZ8c95C0sgS+7jCIT5qoA5w="
 file_glob: true
  file: "fabscanpi_basic_jessie_${TRAVIS_TAG}.zip"
  on:
    tags: true
    repo: mariolukas/FabScanPi-Build-Raspbian
